### ISSUE TITLE
Settings for cutting papers

### ISSUE THREAD

**Issue by jcolomb** [fab-machines/Fabulaser-Mini#6]
Did you ever try to cut papers (we plan to create book marks as goodies). 

Any tips on the settings we should try ?

**Comment by satshas** [comment]
Hello there,

We have been successful in cutting materials like "Finnpappe" "Finncardboard", thick paper (>=0.5mm) and normal cardboard.

As a starting point you could try the following:

- power between 10 and 20%
- speed between 3 and 10%
